# Generated by Django 3.1.7 on 2021-02-26 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='players',
            name='county',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='players',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
