# Generated by Django 3.1.7 on 2021-02-26 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa_app', '0002_auto_20210226_1242'),
    ]

    operations = [
        migrations.RenameField(
            model_name='players2',
            old_name='county',
            new_name='name',
        ),
    ]
