# Generated by Django 3.1.7 on 2021-02-26 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa_app', '0004_auto_20210226_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players',
            name='date',
            field=models.CharField(max_length=30),
        ),
    ]
