# Generated by Django 3.1.7 on 2021-02-26 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa_app', '0005_auto_20210226_1223'),
        ('mpesa_app', '0003_auto_20210226_1243'),
    ]

    operations = [
    ]
